export const passages = [
  "the quick brown fox jumps over the lazy dog near the riverbank at dawn",
  "success is not final failure is not fatal it is the courage to continue that counts",
  "artificial intelligence is transforming how we write code and build applications",
  "a quiet mind can hear the intuitive whispers of wisdom amid the daily chaos",
  "good design is making something intelligible and memorable for the end user",
  "learning to type faster requires consistent practice and focus on accuracy first",
  "the view from the top of the mountain made the grueling climb entirely worthwhile",
  "she found a hidden path through the dense forest leading to a crystal clear lake",
  "innovation distinguishes between a true leader and a follower in the market",
  "bright neon lights flickered brightly against the dark rainy city streets tonight",
  "he packed his bags and decided to travel across the country with no specific plan",
  "writing clean documentation is just as important as writing functional software",
  "the rhythmic sound of ocean waves crashing against the shore brought instant peace",
  "curiosity is the engine of achievement that drives human progress forward daily",
  "simple layouts often provide the most elegant user experiences on mobile devices",
  "an open window let in a cool breeze along with the faint smell of blooming jasmine",
  "consistency over intensity is the secret ingredient to mastering any new skill",
  "they gathered around the warm campfire to share stories under a starry night sky",
  "unexpected challenges frequently reveal the hidden depths of our true character",
  "patience and persistence are essential virtues when debugging complex algorithms",
];
